version: '3.8'

services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - node

  node:
    image: node:14
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    command: npm install
